import { FixedFooter, Footer } from './Footer';
import { Header } from './Header';
import {
  Interior2ndSection,
  InteriorConstruction,
  InteriorConsultationSection,
  InteriorCourse,
  InteriorDocument,
  InteriorHero,
  InteriorOffice,
  InteriorSchedule,
  InteriorStartup,
  OfficePortfolio,
} from './InteriorPage';
import {
  OperationChartSection,
  OperationHero,
  OperationSection4th,
  OperationSection5th,
  OperationSection6th,
  OperationSection7th,
  OperationSlider,
} from './OperationPage';
import { CleaningHero,
  CleaningSection,
  CleaningSection2nd,
  CleaningSection3rd,
  CleaningSection4th,
  CleaningSection5th,
  CleaningSection6th,
  CleaningSection7th,
  CleaningSection8th,
  CleaningSection9th,
  CleaningSection10th,
  CleaningSection11th
 } from './CleaningPage';
import {  PostList } from './BlogPage';
import { PostDetail } from './PostDetail';
import { ReviewList } from './ReviewPage';
export {
  OperationHero,
  Footer,
  FixedFooter,
  Header,
  OperationSlider,
  OperationChartSection,
  OperationSection4th,
  OperationSection5th,
  OperationSection6th,
  OperationSection7th,
  InteriorHero,
  Interior2ndSection,
  InteriorConsultationSection,
  InteriorConstruction,
  InteriorDocument,
  InteriorSchedule,
  InteriorCourse,
  InteriorOffice,
  InteriorStartup,
  OfficePortfolio,
  CleaningHero,
  CleaningSection,
  CleaningSection2nd,
  CleaningSection3rd,
  CleaningSection4th,
  CleaningSection5th,
  CleaningSection6th,
  CleaningSection7th,
  CleaningSection8th,
  CleaningSection9th,
  CleaningSection10th,
  CleaningSection11th,
  PostList,
  PostDetail,
  ReviewList
};
